version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: armario_db
    environment:
      POSTGRES_DB: armariodb
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - armario-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: armario_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/armariodb
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: postgres_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - armario-network

networks:
  armario-network:
    driver: bridge

volumes:
  postgres_data: 